# Generated by Django 5.2.3 on 2025-08-13 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('credit', 'Credit Card'), ('savings', 'Savings'), ('investment', 'Investment'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('health', 'Healthcare'), ('education', 'Education'), ('utilities', 'Utilities'), ('rent', 'Rent/Mortgage'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterModelTable(
            name='expense',
            table=None,
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('credit', 'Credit Card'), ('savings', 'Savings'), ('investment', 'Investment'), ('other', 'Other')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
