# Generated by Django 5.2.3 on 2025-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_expense_account_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer')], default='expense', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='transfer_from',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='transfer_to',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('health', 'Healthcare'), ('education', 'Education'), ('utilities', 'Utilities'), ('rent', 'Rent/Mortgage'), ('insurance', 'Insurance'), ('other', 'Other'), ('salary', 'Salary'), ('freelance', 'Freelance'), ('investment', 'Investment Returns'), ('gift', 'Gift'), ('refund', 'Refund'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
